services:
  - type: web
    name: integration-mock
    autoDeploy: false
    healthCheckPath: /healthz
    env: docker
    dockerfilePath: ./Dockerfile
    region: frankfurt
    envVars:
      - key: TEMPORAL_HOST
        fromService:
          name: temporal
          type: pserv
          property: host
